USE gold;

SELECT *
FROM SALES_DATA
LIMIT 10;

# for changing names
ALTER TABLE SALES_DATA
RENAME COLUMN `Date` TO SALES_DATE,
RENAME COLUMN `Store ID` TO STORE_ID,
RENAME COLUMN `Product ID` TO PRODUCT_ID,
RENAME COLUMN `Category` TO CATEGORY,
RENAME COLUMN `Region` TO REGION,
RENAME COLUMN `Inventory Level` TO INVENTORY_LEVEL,
RENAME COLUMN `Units Sold` TO UNITS_SOLD,
RENAME COLUMN `Units Ordered` TO UNITS_ORDERED,
RENAME COLUMN `Price` TO PRICE,
RENAME COLUMN `Discount` TO DISCOUNT,
RENAME COLUMN `Weather Condition` TO WEATHER_CONDITION,
RENAME COLUMN `Promotion` TO PROMOTION,
RENAME COLUMN `Competitor Pricing` TO COMPETITOR_PRICING,
RENAME COLUMN `Seasonality` TO SEASONALITY,
RENAME COLUMN `Epidemic` TO EPIDEMIC,
RENAME COLUMN `Demand` TO DEMAND;

# more alteration based on definitions
ALTER TABLE SALES_DATA
RENAME COLUMN CATEGORY TO PRODUCT_CATEGORY;

-- total rows
SELECT COUNT(*) AS total_rows
FROM SALES_DATA;

#
DESCRIBE SALES_DATA;
-- Result much values are of text type so we will change them to text

-- 13
ALTER TABLE SALES_DATA
MODIFY SALES_DATE DATE;

-- 14 creating other columns from date column 
SELECT * 
FROM SALES_DATA
WHERE SALES_DATE IS NULL;
-- no null values

-- 15 creating new column for sure 


-- 16 changing other text columns
SELECT 
COUNT(DISTINCT STORE_ID) AS DISTINCT_STORES,
COUNT(DISTINCT PRODUCT_ID) AS DISTINCT_PRODUCTS,
COUNT(DISTINCT PRODUCT_CATEGORY) AS DISTINCT_PRODUCT_CAT,
COUNT(DISTINCT REGION) AS DISTINCT_REGION,
COUNT(DISTINCT WEATHER_CONDITION) AS DISTINCT_WEATHER, 
COUNT(DISTINCT SEASONALITY) AS DISTINCT_SEASONALITY
FROM SALES_DATA;

-- we will convert product category, region, weather, seasonality into ids
ALTER TABLE SALES_DATA 
ADD REGION_ID INT,
ADD PRODUCT_CAT_ID INT,
ADD WEATHER_ID INT, 
ADD SEASONALITY_ID INT;

ALTER TABLE SALES_DATA
DROP COLUMN REGION_ID,
DROP COLUMN PRODUCT_CAT_ID,
DROP COLUMN WEATHER_ID,
DROP COLUMN SEASONALITY_ID;

DESCRIBE SALES_DATA;

SELECT *
FROM SALES_DATA
WHERE
SALES_DATE IS NULL OR
STORE_ID IS NULL OR
PRODUCT_ID IS NULL OR
PRODUCT_CATEGORY IS NULL OR
REGION IS NULL OR
INVENTORY_LEVEL IS NULL OR
UNITS_SOLD IS NULL OR
UNITS_ORDERED IS NULL OR
PRICE IS NULL OR
DISCOUNT IS NULL OR
WEATHER_CONDITION IS NULL OR
PROMOTION IS NULL OR
COMPETITOR_PRICING IS NULL OR
SEASONALITY IS NULL OR
EPIDEMIC IS NULL OR
DEMAND IS NULL;

-- now the data is clean lets take it back to ml 











